In [1]:
import numpy as np

rows = 20000
cols = 10000

data = np.random.randint(0, 100, size=(rows, cols))

np.savetxt("data.csv", data, delimiter=",", fmt="%d")

print("Data file created successfully")


Data file created successfully


In [2]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [0, 0, 0],
    [0, 0, 0]
])

for i in range(1, matrix.shape[0]):
    matrix[i] = matrix[0]

print(matrix)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [3]:
import numpy as np

arr = np.array([1, 2, 1, 3, 2, 1, 3, 3])

unique_elements = np.unique(arr)

grouped_matrix = []

for elem in unique_elements:
    grouped_matrix.append(arr[arr == elem])

print(grouped_matrix)


[array([1, 1, 1]), array([2, 2]), array([3, 3, 3])]


In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

add = A + B

sub = A - B

print("Add:\n", add)
print("Sub:\n", sub)


Add:
 [[ 6  8]
 [10 12]]
Sub:
 [[-4 -4]
 [-4 -4]]


In [5]:
import numpy as np

n = 4
matrix = np.zeros((n, n), dtype=int)

matrix[0][0] = 2
matrix[0][n-1] = 4
matrix[n-1][0] = 6
matrix[n-1][n-1] = 8

print(matrix)


[[2 0 0 4]
 [0 0 0 0]
 [0 0 0 0]
 [6 0 0 8]]


In [6]:
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

row_sum = []

for row in matrix:
    row_sum.append(sum(row))

print(tuple(row_sum))


(6, 15, 24)
